/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package contacts;

import static contacts.Home.showMessage;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

/**
 *
 * @author carlosalberto
 */
public class Find extends javax.swing.JFrame {

    /**
     * Creates new form Find
     */
    public Find() {
        initComponents();
        try {
            this.setIconImage(ImageIO.read(getClass().getResource("img/contact.png")));
//            this.setIconImage(ImageIO.read(new File("img/java_cup.png")));
        }
        catch (IOException exc) {
            exc.printStackTrace();
        }
               
        this.setBounds(225, 300, 300, 300);
        this.pack();//ajustar tamaño de ventana al contenido.
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        edtFind = new javax.swing.JTextField();
        btnFind = new javax.swing.JButton();

        setTitle("Buscar Contacto");
        setAlwaysOnTop(true);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Introdusca el nombre:"));

        edtFind.setNextFocusableComponent(btnFind);

        btnFind.setText("Buscar");
        btnFind.setNextFocusableComponent(edtFind);
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(edtFind, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFind)
                .addGap(112, 112, 112))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFind))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        // TODO add your handling code here:
        
        if(edtFind.getText().length() > 0){            
        
        try {
            
            Class.forName("com.mysql.jdbc.Driver");            
            Connection conn = DriverManager.getConnection("jdbc:mysql://127.0.0.1/contacts", "root", "");
            System.out.println("Conexion exitosa...");            
            
//            String sql = "SELECT name, phone, email FROM contact WHERE name=?";
            String sql2 = "SELECT * FROM contact WHERE name LIKE '%" + edtFind.getText() + "%'";
//            String sql3 = "SELECT * FROM contact WHERE name LIKE '%Car%'";
            
//            PreparedStatement pst = conn.prepareStatement(sql);
//            pst.setString(1,edtFind.getText());
            
            PreparedStatement pst2 = conn.prepareStatement(sql2);
//            pst2.setString(1,edtFind.getText());
            ResultSet result = pst2.executeQuery();
            
            if(result.first()){
                contacts.Home.setContactName(result.getString("name"));
                contacts.Home.setContactPhone(result.getString("phone"));
                contacts.Home.setContactEmail(result.getString("email"));
                contacts.Home.setSelectedID(Integer.parseInt(result.getString(1))); //id               
                contacts.Home.getDBData();
            }
            else
                showMessage(this, "Buscar Contacto", "No se encontró ningun contacto con ese nombre.",JOptionPane.WARNING_MESSAGE);

//            while (result.next()){                        
//                System.out.println(result.getString(1)+"\t"+result.getString(2)+"\t"+result.getString(3));
//            } 
            this.setVisible(false);
        } 
        catch (SQLException sqlex) {
            System.out.println("MySQL Error: "+sqlex.toString());
//            statusBar.setText("MySQL Error: "+sqlex.getMessage());
        }   
        catch (ClassNotFoundException err) {
            err.printStackTrace();
//            statusBar.setText("ClassNotFoundException: "+"No se encuentra la Clase especificada: "+err.getMessage());
        }                
        catch (Exception ex) {
            System.out.println("se ha producido un error inesperado: "+ex.getMessage());
//            statusBar.setText("Error: Se ha producido un error inesperado: "+ex.getMessage());
        }
        
        }
        else
            contacts.Home.showMessage(this, "Buscar Contacto","Debe insertar primero el nombre antes de realizar una búsqueda!",JOptionPane.WARNING_MESSAGE);
       
        
    }//GEN-LAST:event_btnFindActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Find.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Find.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Find.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Find.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Find().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFind;
    private javax.swing.JTextField edtFind;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
